sudo: required
dist: xenial
language: cpp

git:
  submodules: true

matrix:
  include:
  - os: linux
    compiler: gcc-7
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-7', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python', 'python-nose', 'python-jinja2', 'python-pip']
    install: export CXX="g++-7"

  - os: linux
    compiler: gcc-8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev', 'libboost-dev', 'python', 'python-nose', 'python-jinja2', 'python-pip']
    install: export CXX="g++-8"
    env:

  - os: osx
    compiler: gcc-9
    before_install:
      - brew update
      - brew install gcc@9
    install: export CXX="g++-9"
    env: CMAKE_ARGS="-DLAMBDA_FASTBUILD=1"

script:
  - mkdir -p build && cd build
  - cmake .. -DLAMBDA_NATIVE_BUILD=0 -DLAMBDA_COMPILE_THREADS=2 ${CMAKE_ARGS}
  - travis_wait make VERBOSE=1 # need to prefix with travis_wait because it might take > 10min
  - ctest .
