sudo: required
dist: trusty
language: cpp
#cache:
  #- directories:
    #- $HOME/ccache
matrix:
  include:
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-4.9', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev']
      install: ['export CXX="g++-4.9"' ]
      before_script:
        - sudo dd if=/dev/zero of=/swapfile bs=64M count=32 # cheat us some extra MEM
        - sudo mkswap /swapfile
        - sudo swapon /swapfile
      after_script:
        - sudo swapoff /swapfile
        - sudo rm /swapfile

    - os: linux
      compiler: gcc-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-5', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev']
      install: ['export CXX="g++-5"' ]
      before_script:
        - sudo dd if=/dev/zero of=/swapfile bs=64M count=32 # cheat us some extra MEM
        - sudo mkswap /swapfile
        - sudo swapon /swapfile
      after_script:
        - sudo swapoff /swapfile
        - sudo rm /swapfile

    #- os: linux
      #compiler: gcc-6
      #addons:
          #apt:
          #sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          #packages: ['g++-6', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev']
      #install: ['export CXX="g++-6"' ]
      #before_script:
          #- sudo dd if=/dev/zero of=/swapfile bs=64M count=32 # cheat us some extra MEM
          #- sudo mkswap /swapfile
          #- sudo swapon /swapfile
      #after_script:
          #- sudo swapoff /swapfile
          #- sudo rm /swapfile

    - os: linux
      compiler: clang-3.8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8', 'g++-4.9', 'cmake', 'cmake-data', 'zlib1g-dev', 'libbz2-dev'] # g++ required for newer libstdc++
      install: ['export CXX="clang++-3.8"' ]

    - os: osx
      compiler: gcc-4.9
      before_install:
        - sudo brew update
        - sudo brew tap homebrew/versions
        - sudo brew install gcc49
      install: ['export CXX="g++-4.9"' ]

    - os: osx
      compiler: gcc-6
      before_install:
        - sudo brew update
        - sudo brew tap homebrew/versions
        - sudo brew install gcc6
      install: ['export CXX="g++-6"' ]

    #- os: osx
      #compiler: clang-3.6
      #before_install:
        #- sudo brew update
        #- sudo brew tap homebrew/versions
        #- sudo brew install llvm36
      #install: ['export CXX="clang++-3.6"' ]

    #- os: osx
      #compiler: clang-3.7
      #before_install:
        #- sudo brew update
        #- sudo brew tap homebrew/versions
        #- sudo brew install llvm37
      #install: ['export CXX="clang++-3.7"' ]

#before_script:
  #- export PATH=$HOME/.local/bin:$PATH
  #- rm -rf ${HOME}/.ccache
  #- mkdir -p ${HOME}/ccache/${TRAVIS_BRANCH}/${TRAVIS_OS_NAME}/${CXX}
  #- ln -s  ${HOME}/ccache/${TRAVIS_BRANCH}/${TRAVIS_OS_NAME}/${CXX} ${HOME}/.ccache
  #- ln -s /usr/bin/ccache ${HOME}/.local/bin/${CXX}
script:
  #- ccache -s
  - mkdir -p build && cd build
  - cmake ..
  - make lambda_indexer
  - travis_wait make lambda # need to prefix with travis_wait because it might take > 10min
  - ctest .