sudo: required
dist: trusty
language: cpp
cache: ccache
cache:
  directories:
    - $HOME/.ccache
matrix:
  include:
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'cmake', 'zlib1g-dev', 'libbz2-dev']
      install: ['export PATH=/usr/lib/ccache:$PATH', 'export CXX="g++-4.9" CC="gcc-4.9"' ]
      before_script:
        - sudo dd if=/dev/zero of=/swapfile bs=64M count=32 # cheat us some extra MEM
        - sudo mkswap /swapfile
        - sudo swapon /swapfile
      after_script:
        - sudo swapoff /swapfile
        - sudo rm /swapfile

    - os: linux
      compiler: gcc-5
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'cmake', 'zlib1g-dev', 'libbz2-dev']
      install: ['export PATH=/usr/lib/ccache:$PATH', 'export CXX="g++-5" CC="gcc-5"' ]
      before_script:
        - sudo dd if=/dev/zero of=/swapfile bs=64M count=32 # cheat us some extra MEM
        - sudo mkswap /swapfile
        - sudo swapon /swapfile
      after_script:
        - sudo swapoff /swapfile
        - sudo rm /swapfile

    #- os: linux
      #compiler: gcc-6
      #addons:
          #apt:
          #sources: ['ubuntu-toolchain-r-test']
          #packages: ['g++-6', 'cmake', 'zlib1g-dev', 'libbz2-dev']
      #install: ['export CXX="g++-6" CC="gcc-6"' ]
      #before_script:
          #- sudo dd if=/dev/zero of=/swapfile bs=64M count=32 # cheat us some extra MEM
          #- sudo mkswap /swapfile
          #- sudo swapon /swapfile
      #after_script:
          #- sudo swapoff /swapfile
          #- sudo rm /swapfile

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang', 'g++-4.9', 'cmake', 'zlib1g-dev', 'libbz2-dev'] # g++ required for newer libstdc++
      install: ['export PATH=/usr/lib/ccache:$PATH']

    #- os: osx
      #compiler: clang-3.6
      #before_install:
        #- sudo brew update
        #- sudo brew tap homebrew/versions
        #- sudo brew install llvm36
      #install: ['export CXX="clang++-3.6" CC="clang-3.6"' ]

    #- os: osx
      #compiler: clang-3.7
      #before_install:
        #- sudo brew update
        #- sudo brew tap homebrew/versions
        #- sudo brew install llvm37
      #install: ['export CXX="clang++-3.7" CC="clang-3.7"' ]

script:
  - mkdir -p build && cd build
  - cmake ..
  - make lambda_indexer
  - travis_wait make lambda # need to prefix with travis_wait because it might take > 10min
  - ctest .