sudo: required
dist: trusty
language: cpp
compiler:
  - gcc-5
#  - gcc-4.9
  - clang
cache:
  apt: true
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    #- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
addons:
  apt:
    sources:
      #- llvm-toolchain-trusty
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      #- gcc-4.9
      #- g++-4.9
      - gcc-5
      - g++-5
      - clang
      - zlib1g-dev
      - libbz2-dev
script:
  ./util/travis/linux-cibuild.sh